### ISSUE TITLE
TraceId is not propageted when using dapr grpc client's InvokeMethodAsync method

### ISSUE THREAD

**Issue by quickstar** [dapr/dotnet-sdk#568] opened 2021-01-28 11:15 UTC
It seems that the W3C trace headers in dapr grpc calls are not propagated correctly.

I have a simple API Gateway where the W3C Activity format is specified like:
```c#
Activity.DefaultIdFormat = ActivityIdFormat.W3C;
```
The API Gateway is executing subsequent calls to several microservices, either via dapr http/grpc or vanilla grpc with generated proto files from .net (no dapr is involved).

## Expected Behavior
If I execute a call via Rest to the ApiGateway-->Dapr-->REST-WeatherMicroservice as shown in the below log:
![image](https://user-images.githubusercontent.com/1195919/106128813-0135f480-6160-11eb-8bc1-7d2f33790b2e.png)
The Trace Id is propagated correctly and the request correlation can be made.

If I execute a call via Rest to the ApiGateway-->Vanilla Grpc-->Grpc-WeatherMicroservice as shown in the below log:
![image](https://user-images.githubusercontent.com/1195919/106129323-70abe400-6160-11eb-8d77-521ecd96c421.png)
The Trace Id is propagated correctly and the request correlation can be made.

## Actual Behavior
If I execute a call via Rest to the ApiGateway-->Dapr-->Grpc-WeatherMicroservice as shown in the below log:
![image](https://user-images.githubusercontent.com/1195919/106129688-c54f5f00-6160-11eb-83d3-c157e3dcf7ea.png)
The Trace Id is broken and Dapr generates a new TraceId which breaks the request correlation.

## Steps to Reproduce the Problem
See example project: https://gitlab.com/quickstar1/microservice-prototype

## Release Note

RELEASE NOTE:

**Comment by yaron2** [comment] 2021-01-29 15:48
Which Dapr version are you using?

**Comment by quickstar** [comment] 2021-01-29 15:52
> 
> 
> Which Dapr version are you using?

I'm using Dapr Runtime v1.0.0-rc.3 with the latest sdk available

**Comment by rynowak** [comment] 2021-01-29 23:34
thanks @quickstar - I was able to reproduce this issue using the Dapr v1.0.0-rc3 runtime and v1.0.0-rc2 SDK. There are some changes to how these APIs behave in RC3 but nothing that should impact tracing. 

What's happening here is that the `grpc-trace-bin` metadata is being passed (but not `traceparent`) when Dapr invokes a gRPC server. ASP.NET Core has no understanding of `grpc-trace-bin`, and doesn't populate an activity based on it.

Here's basically what happens:

```
browser ->
API Gateway (T1) // The api gateway doesn't see a value for traceparent and so it generates a new trace ID
API Gateway Dapr Sidecar (T1) // Sees the traceparent value and forwards it
Weather Dapr Sidecar (T1) // Sees the traceparent value and forwards it as grpc-trace-bin
Weather (T2) // Doesn't see a value for traceparent so it generates a new trace ID
```

**Comment by rynowak** [comment] 2021-01-30 00:47
Thanks for the report @quickstar - we confirmed that this is a bug in the Dapr runtime and we'll use dapr/dapr#2749 to track the fix.

I'm going to close this issue since there's no fix needed in the .NET SDK

**Closed by rynowak** 2021-01-30 00:47 UTC
Labels: kind/bug

**Comment by pkedy** [comment] 2021-03-05 18:12
Hey @quickstar, the [link to your example project](https://gitlab.com/quickstar1/microservice-prototype) is giving me a 404. Can you double check the permissions on it? I'd like to use it to validate the potential fix I have. Thanks!
