### ISSUE TITLE
Actor Proxy does not use same JsonSerializerOptions when deserializing in the non remoting API

### ISSUE THREAD

**Issue by techgeek03** [dapr/dotnet-sdk#664] opened 2021-04-29 09:51 UTC
## Expected Behavior

When using `ActorProxy Create(ActorId actorId, string actorType, ActorProxyOptions options = null);` with custom  `ActorProxyOptions`  for the `JsonSerializerOptions` then `ActorProxy.InvokeMethodAsync` should use the same `JsonSerializerOptions ` for Deserializaton.

https://github.com/dapr/dotnet-sdk/blob/1e23165d1c651c0c938f7efbd3561a5014501fb2/src/Dapr.Actors/Client/ActorProxy.cs#L117

should be changed to  `return await JsonSerializer.DeserializeAsync<TResponse>(response, JsonSerializerOptions);`

## Actual Behavior

Since there are discrepancies in the serialization and desalinization the call is successful in the actor but fails to deserialize on the client side. 

## Release Note

RELEASE NOTE:

**Comment by rynowak** [comment] 2021-04-30 20:25
I can confirm that this is a bug - we should be using the configured settings.

**Comment by rynowak** [comment] 2021-05-01 00:15
Fixed in master for 1.2. Reopening this until I cut a 1.1.2 patch release with this fix.

**Comment by techgeek03** [comment] 2021-05-01 09:13
Thanks @rynowak this is awesome 👍

**Comment by akourbat** [comment] 2021-05-12 20:29
Just to add - `ActorHost` has its own serializer settings which are read-only.  For example `Host.JsonSerializerOptions.DefaultIgnoreCondition` defaults to `Never`.  Is this intended?  I'd love to be able to set this to `JsonIgnoreCondition.WhenWritingNull` for example.  Is this part of the issue that is being resolved with 1.2 or should I open new issue?

**Comment by rynowak** [comment] 2021-05-13 18:07
> EDIT: Apologies, I found a way to configure ActorHost serializer via services.AddActors(o => o.JsonSerializerOptions = jOptions);

Yes, this is the right way. All of the serialization settings must be configurable.

**Comment by rynowak** [comment] 2021-09-28 20:47
This was done in 1.1

**Closed by rynowak** 2021-09-28 20:47 UTC
Labels: kind/bug
