### ISSUE TITLE
Reminder stops working

### ISSUE THREAD

**Issue by ddobric** [dapr/dotnet-sdk#423] opened 2020-10-11 07:03 UTC
I have registered reminder and implemented *IRemindable*. All was working for a while.
Unfortunatelly, after some time (i.e. service restart) I get following error:

_level=error msg="could not find active reminder with key: MachineActor||2||MyReminder" app_id=machineactor instance=MACHINEXYZ scope=dapr.runtime.actor type=log ver=0.11.0_

I'm I doing something wrong or is this a bug? According to the spec, a reminder should be persistable.

**Comment by vinayada1** [comment] 2020-10-13 20:50
Yes, reminders should be persistent. Could you check the actor state store to see if you see the reminder stored? Also, could you add dapr startup logs here?

**Comment by vinayada1** [comment] 2020-10-22 21:29
@ddobric - Could you check if the issue you reported is similar to:-
https://github.com/dapr/dotnet-sdk/issues/435

Are the repro steps similar?

**Comment by ddobric** [comment] 2020-10-27 20:49
I'm not sure if it is the same kind of the issue. Referenced issues is related to the timer pattern. My issue is related to reminders. 
It might be I do something wrong or there is some issue with reminders. 
Is there any example that I can try?

Thanks
Damir

**Comment by vinayada1** [comment] 2020-11-17 19:08
Yes but I meant are the steps to reproduce the issue the same as in #435

**Comment by vinayada1** [comment] 2021-01-06 18:39
@ddobric  - Is this still an issue with the latest Dapr release?

**Comment by rynowak** [comment] 2021-02-27 01:21
We've identified an issue at the runtime level that is likely the root cause of this. https://github.com/dapr/dapr/issues/2705

I'm closing this issue since there's nothing to do here.

**Closed by rynowak** 2021-02-27 01:21 UTC
Labels: area/actor, question
