### ISSUE TITLE
New gRPC DaprClient fails for Secret API requests if mTLS is enabled 

### ISSUE THREAD

**Issue by cmendible** [dapr/dotnet-sdk#261] opened 2020-03-19 17:28 UTC
## Expected Behavior

DaprClient should work with mTLS enabled.

## Actual Behavior

clients created through the builder:

```chsharp
var client = new DaprClientBuilder().Build();
```

Fail to get secrets through calling `client.GetSecretAsync` when Dapr mTLS is enabled.

## Steps to Reproduce the Problem

Deploy the following yaml to K8s:

```yaml
---
# Create a Kubernetes Secret
apiVersion: v1
kind: Secret
metadata:
  name: super-secret
  namespace: default
type: Opaque
data:
  super-secret: eW91ciBzdXBlciBzZWNyZXQK

---
# If RBAC is enabled in K8s, give the default SA access to secrets in the default namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dapr-secret-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
```

Create and deploy an ASP.NET Core application which implements the following call:

```chshap
var secrets = await client.GetSecretAsync("kubernetes", "super-secret", new Dictionary<string, string>() { { "namespace", "default" } });
```

The call will fail with mTLS enabled.

**Comment by amanbha** [comment] 2020-03-19 17:42
@cmendible I believe, it would not be specific to dotnet sdk as the calls from user service code to Dapr is not secured.

**Comment by cmendible** [comment] 2020-03-19 17:44
@amanbha should I post a bug or question on the Dapr repo?

**Comment by amanbha** [comment] 2020-03-19 17:47
> @amanbha should I post a bug or question on the Dapr repo?

Yes, it would be in dapr/dapr repo as the calls to dapr sidecar from user service code is not secured. Is the issue only with secret api or with any api?

**Comment by cmendible** [comment] 2020-03-19 17:52
Roger that. 

Only tested the secret api.

**Comment by yaron2** [comment] 2020-03-19 20:03
I closed the issue on `dapr/dapr` *for now* as this is likely an SDK usage issue with gRPC.

Notice the client config used here to talk to Dapr from a client when gRPC is enabled:
https://github.com/dapr/docs/blob/master/howto/create-grpc-app/README.md#invoking-dapr---go-example

Look at the mTLS enabled part. You need to provide a TLS config with `InsecureSkipVerify`.

**Comment by yaron2** [comment] 2020-03-19 20:05
I was able to invoke Dapr for the Get Secrets API over gRPC with mTLS enabled using the client config mentioned in the doc above.

**Comment by amanbha** [comment] 2020-03-19 20:46
Thanks @yaron2, jsut for my understanding, why that config is required, calls from Sercive->Dapr don't use mTLS. Only calls between Dapr<->DApr use mTLS.

**Comment by yaron2** [comment] 2020-03-19 20:49
> Thanks @yaron2, for my understanding, why that config is required, calls from Sercive->Dapr don't use mTLS. Only calls between Dapr<->DApr use mTLS.

When mTLS is enabled in Dapr, it's configured that the app can call Dapr without mTLS. There's a specific way that gRPC dictates that you should do it. So in the document above, it details on the config you need for the client. If you look at the example you'll see the client doesn't actually provide any certificate in the call to Dapr.

**Comment by amanbha** [comment] 2020-03-19 21:03
> > Thanks @yaron2, for my understanding, why that config is required, calls from Sercive->Dapr don't use mTLS. Only calls between Dapr<->DApr use mTLS.
> 
> When mTLS is enabled in Dapr, it's configured that the app can call Dapr without mTLS. There's a specific way that gRPC dictates that you should do it. So in the document above, it details on the config you need for the client. If you look at the example you'll see the client doesn't actually provide any certificate in the call to Dapr.

If enabling mTLS doesnt change the behavior of http calls, it should not change the behavior of gRPC calls. SDKs or clients have no way of knowing whether the code is running with Dapr mTLS enabled or not so it can't conditionally set it. When user has to create it conditionally when deploying to K8s, it breaks the scenario of same code running on dev a machine and in K8s.

Is it a side affect of the fact that same gRPC channel is used app for App->Dapr & Dapr->Dapr communication and mTLS is enabled for it. Perhaps its time to seprate it so tht different settingx can be applied to them.

**Comment by yaron2** [comment] 2020-03-19 21:16
It's a side effect of it yes, which is a side effect of how gRPC behaves when you apply a "verify only if cert is given to you".

Maybe it is time to separate it. I'll create an issue for it for 0.6.0.

**Comment by yaron2** [comment] 2020-03-19 21:23
https://github.com/dapr/dapr/issues/1293

**Comment by amanbha** [comment] 2020-03-19 21:25
> It's a side effect of it yes, which is a side effect of how gRPC behaves when you apply a "verify only if cert is given to you".
> 
> Maybe it is time to separate it. I'll create an issue for it for 0.6.0.

Great, thanks @yaron2 !, users wont have to create grpc connection conditionally.

@cmendible It will be fixed in the runtime for 0.6.0, how do you want to handle it for 0.5.0 in the meantime so that same code runs locally on dev box and in k8s with mTLS. I am open to releasing a nuget package with the fix so that things continue to work on 0.5.0

**Comment by cmendible** [comment] 2020-03-19 21:48
@amanbha yes please release a fix for 0.5.0

**Comment by amanbha** [comment] 2020-03-19 22:51
> @amanbha yes please release a fix for 0.5.0

Sure @cmendible . I was thinking about it and could you try following:
`
var client = new DaprClientBuilder()
                .UseEndpoint("https://127.0.0.1:50001")
                .Build();
`

**Comment by cmendible** [comment] 2020-03-20 10:40
> > @amanbha yes please release a fix for 0.5.0
> 
> Sure @cmendible . I was thinking about it and could you try following:
> `var client = new DaprClientBuilder() .UseEndpoint("https://127.0.0.1:50001") .Build();`

That results in _Error starting gRPC call: The SSL connection could not be established, see inner exception._

**Comment by yaron2** [comment] 2020-03-20 10:56
The gRPC channel would need to have empty credentials passed to it:

new SslCredentials()

**Comment by cmendible** [comment] 2020-03-20 14:54
This is what is working for me using the client provide by gRPC:

```csharp
using (var httpClientHandler = new HttpClientHandler())
{
	httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, sslPolicyErrors) =>
	{
		return true;
	};
	using (var httpClient = new HttpClient(httpClientHandler))
	{
		var channel = GrpcChannel.ForAddress("https://127.0.0.1:50001", new GrpcChannelOptions()
		{
			HttpClient = httpClient
		});
		var dapr = new Dapr.Client.Autogen.Grpc.Dapr.DaprClient(channel);
		var envelope = new Dapr.Client.Autogen.Grpc.GetSecretEnvelope()
		{
			Key = "super-secret",
			StoreName = "kubernetes"
		};
		envelope.Metadata.Add("namespace", "default");
		var secreValue = dapr.GetSecret(envelope).Data["super-secret"];

		context.Response.ContentType = "application/json";
		await JsonSerializer.SerializeAsync(context.Response.Body, secreValue);
	}
}
```

The current implementation does no allow me to setup such as configuration.

**Comment by amanbha** [comment] 2020-03-20 17:11
> This is what is working for me using the client provide by gRPC:
> 
> ```cs
> using (var httpClientHandler = new HttpClientHandler())
> {
> 	httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, sslPolicyErrors) =>
> 	{
> 		return true;
> 	};
> 	using (var httpClient = new HttpClient(httpClientHandler))
> 	{
> 		var channel = GrpcChannel.ForAddress("https://127.0.0.1:50001", new GrpcChannelOptions()
> 		{
> 			HttpClient = httpClient
> 		});
> 		var dapr = new Dapr.Client.Autogen.Grpc.Dapr.DaprClient(channel);
> 		var envelope = new Dapr.Client.Autogen.Grpc.GetSecretEnvelope()
> 		{
> 			Key = "super-secret",
> 			StoreName = "kubernetes"
> 		};
> 		envelope.Metadata.Add("namespace", "default");
> 		var secreValue = dapr.GetSecret(envelope).Data["super-secret"];
> 
> 		context.Response.ContentType = "application/json";
> 		await JsonSerializer.SerializeAsync(context.Response.Body, secreValue);
> 	}
> }
> ```
> 
> The current implementation does no allow me to setup such as configuration.

Thanks for sharing it @cmendible I will look into whats the best option to enable it temporarily until 0.6.0 when the linked runtime issue will be fixed to hanlde this. Till then the code has to be different when running with & without mTLS.

**Comment by amanbha** [comment] 2020-03-21 00:05
@cmendible Please see this PR https://github.com/dapr/dotnet-sdk/pull/263 It will be cherry-picked into 0.5.0 branch to release a new nuget package.
The change will be reverted from master branch for 0.6.0 when the issue is fixed in Dapr runtime.

**Comment by cmendible** [comment] 2020-03-21 15:49
> @cmendible Please see this PR #263 It will be cherry-picked into 0.5.0 branch to release a new nuget package to see if it works for you.
> There is an internal method on DaprClientBuilder, its UseGrpcChannelOptions(). I am thinking of making it public to allow for more configurable brhavior form users in future, any feedback around it?
> The change will be reverted from master branch for 0.6.0 when the issue is fixed in Dapr runtime.

LGTM

**Comment by amanbha** [comment] 2020-03-21 20:20
@cmendible  I have published new package version 0.5.0-preview02 witht he changes.

**Comment by cmendible** [comment] 2020-03-21 20:25
@amanbha Thanks that's great news! Should we keep this issue open until 0.6.0 is released?

**Comment by amanbha** [comment] 2020-03-21 20:35
> @amanbha Thanks that's great news! Should we keep this issue open until 0.6.0 is released?

Yes, I have re-opened this issue. Will revert the workaround once we are close to releasing 0.6.0

**Closed** 2020-03-30 17:43 UTC
Labels: P1, kind/bug
