### ISSUE TITLE
How does `builder.Configuration.AddDaprSecretStore` Work?

### ISSUE THREAD

**Issue by sameert89** [dapr/dotnet-sdk#1368] opened 2024-10-16 14:13 UTC
When the app and Dapr start at different times the app has to wait for getting secrets and Dapr has to wait for the app to start listening if I understand it right. This appears like a circular dependency then how exactly does this function work? 

There can be network delay and there is a Wait timeout option which I am guessing is for the time taken to get the secrets.

So does it pause the host startup until then? Sorry for creating this as an issue but I can't seem to find much documentation around it.

**Comment by WhitWaldo** [comment] 2024-10-16 17:00
Host startup is intentionally delayed until the load completes. It shouldn't take that long to retrieve and populate the secrets themselves - the delay is really just waiting for healthiness to be reported, and there shouldn't be much of a delay in a healthy environment.

The timeout value you mentioned puts an upper bound on waiting for failed retries to complete.

**Comment by sameert89** [comment] 2024-10-17 03:27
> Host startup is intentionally delayed until the load completes. It shouldn't take that long to retrieve and populate the secrets themselves - the delay is really just waiting for healthiness to be reported, and there shouldn't be much of a delay in a healthy environment.
> 
> The timeout value you mentioned puts an upper bound on waiting for failed retries to complete.

Thanks for the explanation, but what if the application is started before Dapr? How would the secrets be fetched if Dapr is not ready. I am confused about the circular dependency I mentioned.

**Comment by WhitWaldo** [comment] 2024-10-17 15:32
> > Host startup is intentionally delayed until the load completes. It shouldn't take that long to retrieve and populate the secrets themselves - the delay is really just waiting for healthiness to be reported, and there shouldn't be much of a delay in a healthy environment.
> > The timeout value you mentioned puts an upper bound on waiting for failed retries to complete.
> 
> Thanks for the explanation, but what if the application is started before Dapr? How would the secrets be fetched if Dapr is not ready. I am confused about the circular dependency/race condition I mentioned.
> 
> I read this in an old issue: [#452 (comment)](https://github.com/dapr/dotnet-sdk/issues/452#issuecomment-902983604)
> 
> But can't understand how it's handled, because app won't be up until this function succeeds.

Whoops, yes, I neglected to speak to that. 

Put simply, you cannot use any secrets from the client which might result in such a circular dependency and that makes sense, right?  Take the following example:

- You require an authentication token to communicate with the Dapr sidecar
- You intend to retrieve this token from your remote secret store
- You register your `DaprClient` instance with the DI system and specify that the authentication token should come from your injected `IConfiguration` instance.
- When you configure the secret store using `AddDaprSecretStore`, you create a scope and pass in a DI-retrieved instance of your `DaprClient`

But of course when your code runs through `AddDaprSecretStore`, it'll fault because the key you expect from your `IConfiguration` isn't present because this module was intended to populate it (and it hasn't run yet).

So yes, you have to be careful about specifically which secrets you need and where you're sourcing them especially during startup. Personally, I put my secrets in Azure Key Vault and typically access them via the secret store functionality, except that I specifically register the Dapr API token as a referenced Key Vault Secret in the environment variables for my service (I often use Azure Container Apps here).

By doing this, you can instead opt to read in your environment variables at the top (populating this as authentication happens at the infrastructure level instead):

```cs
var builder = WebApplication.CreateBuilder(args);

builder.Configuration.AddEnvironmentVariables();

builder.Services.AddDaprClient((serviceProvider, daprClientBuilder) => {
  var configuration = serviceProvider.GetRequiredService<IConfiguration>();
  var daprApiToken = configuration["DaprApiToken"];

  daprClientBuilder.UseDaprApiToken(daprApiToken);
});

//...

var app = builder.Build();

//Provision an instance of the DaprClient to use
await using var scope = app.Services.CreateAsyncScope();
var daprClient = scope.Services.GetRequiredService<DaprClient>();

builder.Configuration. AddDaprSecretStore("my-store", [], daprClient);
```

Now if you strictly follow this sort of structure and you're definitely not injecting (and thus not resolving) any other services that need secrets from `IConfiguration`, they'll be pulled at resolution-time and should populate just fine.

**Comment by sameert89** [comment] 2024-10-17 16:00
Thanks for the excellent explanation. So to summarize:
1. We need to keep secrets that can stop `app.build()` accessible in local environment.
2. For other secrets we can call `AddDaprSecretStore()` anytime before `app.Run()` and it will populate it.

So point 2 implies Dapr will serve the secrets even before `app.Run()` is called i.e. application has started listening.

**Comment by sameert89** [comment] 2024-10-17 17:05
Thanks, that clears it all!

**Closed** 2024-10-17 17:05 UTC
Labels: question, area/client/secrets

**Comment by WhitWaldo** [comment] 2024-10-17 17:08
Please don't hesitate to reach out if you have any other questions!
