### ISSUE TITLE
PublishEventAsync results in Grpc.Core.RpcException (Connection refused) even when sidecar running (v1.5.1)

### ISSUE THREAD

**Issue by sjwaight** [dapr/dotnet-sdk#809] opened 2021-12-30 01:49 UTC
## Expected Behavior

Using the DAPR .NET SDK client PublishEventAsync method should work as expected.

### Background 

DAPR sidecar is started just once with these arguments:

```
dapr run --app-id order-service --components-path /home/simon/dapr-workshop/components/local --app-port 5100 --dapr-grpc-port 5101 --dapr-http-port 5180
```

Pubsub component config is

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-workshop.pubsub
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: 127.0.0.1:6379
  - name: redisPassword
    value: ""
```

This code results in an Exception and no message publication.

```csharp
            using var daprClient = new DaprClientBuilder().Build();
            await daprClient.PublishEventAsync("dapr-workshop.pubsub","orders",orderSummary);
```

In the exact same cs file I can implement the above as follows and no error occur and my message is published.

```csharp
            var port = Environment.GetEnvironmentVariable("DAPR_HTTP_PORT");
            var pubsubName= "dapr-workshop.pubsub";
            var topic = "orders";

            using (var httpClient = new HttpClient())
            {
                var result = await httpClient.PostAsync(
                    $"http://127.0.0.1:{port}/v1.0/publish/{pubsubName}/{topic}",
                    new StringContent(JsonSerializer.Serialize(orderSummary), Encoding.UTF8, "application/json")
                );

                _logger.LogInformation($"Order with id {orderSummary.OrderId} published with status {result.StatusCode}!");
            }
```

I can also do a direct HTTP POST with a JSON payload to the DAPR publish endpoint and the message is sent as expected.

## Actual Behavior

When the DAPR .NET SDK client method is used the result is an exception as follows.

```
[2021-12-30 01:29:52.451 ERR] [Serilog.AspNetCore.RequestLoggingMiddleware] HTTP POST /order responded 500 in 2514.4281 ms
Dapr.DaprException: Publish operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
 ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Connection refused SocketException: Connection refused", DebugException="System.Net.Http.HttpRequestException: Connection refused
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
   at Dapr.Client.DaprClientGrpc.MakePublishRequest(String pubsubName, String topicName, ByteString content, Dictionary`2 metadata, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Dapr.Client.DaprClientGrpc.MakePublishRequest(String pubsubName, String topicName, ByteString content, Dictionary`2 metadata, CancellationToken cancellationToken)
   at Vigilantes.DaprWorkshop.OrderService.Controllers.OrderController.NewOrder(CustomerOrder order) in /home/simon/dapr-workshop/Vigilantes.DaprWorkshop.OrderService/csharp/Controllers/OrderController.cs:line 57
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
```
## Steps to Reproduce the Problem

Running on WSL with Windows 11. WSL is running Ubuntu 20.04 and has Docker CE running.

DAPR was installed using `dapr init` and reports itself as v1.5.1

DAPR .NET SDK version is 1.5.0.

.NET SDK version is 3.1.416

## Release Note

RELEASE NOTE:

**Comment by halspang** [comment] 2022-01-06 18:50
@sjwaight - Thanks for opening this issue! Just a few questions.

1. What component are you trying to use?
2. Does this happen immediately, or does it take time to fail? Does it ever work?
3. Are you getting an error in your dapr logs as well?

**Comment by sjwaight** [comment] 2022-01-07 04:10
So after a bit of digging I came across this other closed issue: https://github.com/dapr/dotnet-sdk/issues/609 which makes reference to the need for a GRPC environment variable `DAPR_GRPC_PORT`. 

While I am not using this explicitly in my application it looks like if this missing from the hosted application then you end up in this situation (error) because it looks like the DAPR .NET SDK is defaulting to GRPC. Maybe I missed a config entry somewhere else?

The fix for me was:

1. Ensure that `"DAPR_GRPC_PORT": "5101"` was defined in the runtime environment for my dotnet application.
2. Ensure that dapr was started with this parameter passed `--dapr-grpc-port 5101`

After this the .NET SDK client worked with no issues.

This seems an unexpected behaviour as I am not asking the solution to use GRPC at all yet the client seems to insist on using it when talking to the sidecar. When I simply call the HTTPClient code (as shown in original bug report) it works as expected because I don't allow the client SDK to decide which communication channel to use for the sidecar.

I'm leaving open as I am not sure this behaviour is as expected.

**Comment by halspang** [comment] 2022-01-07 18:08
I believe that this is actually expected. I missed that in your first example there you were running them separately. When you run the sidecar separately, you need to define the environment variables manually.

The .NET SDK also does all of it's communication to Dapr via gRPC. This predates me, but I believe the reasoning here is that the gRPC API is defined via the protobufs, so it can be, at least in part, auto generated.

@rynowak - This is all expected, correct?

**Comment by halspang** [comment] 2022-01-11 21:08
I spoke with @rynowak and he confirmed that this is expected and a documented behavior of `dapr run` closing this issue.

**Closed by halspang** 2022-01-11 21:08 UTC
Labels: kind/bug

**Comment by ChristianWeyer** [comment] 2022-04-27 07:59
Sorry for asking in a closed issue @halspang @rynowak - could you please point me to the documentation of this behavior? We just ran into it, as well ;-)

Thanks!

**Comment by halspang** [comment] 2022-04-27 18:31
@ChristianWeyer  - It's mentioned in the description of the environment variable: https://docs.dapr.io/reference/environment/

**Comment by ChristianWeyer** [comment] 2022-04-27 18:42
Thank you.

I think it needs to be mentioned in a more prominent place, not just in the reference. It is too easy to miss it and makes this mistake.
