### ISSUE TITLE
Add Integration tests to .net sdk repo

### ISSUE THREAD

**Issue by vinayada1** [dapr/dotnet-sdk#389] opened 2020-09-09 20:44 UTC
## Expected Behavior

Add integration tests that can be run end-to-end on every PR.

## Actual Behavior

No end-to-end tests

**Comment by vinayada1** [comment] 2020-11-20 20:18
Especially actors

**Comment by rynowak** [comment] 2020-11-30 21:04
I added a project for in-memory integration tests as part of the DI pr - so we're unblocked for writing tests that don't use the Dapr sidecar. However it would be even better if we can include the interactions with `daprd` like the Java SDK does. We've definitely seen bugs where drift between our expectations and the behavior of `dapr` was the root cause.

**Comment by rynowak** [comment] 2021-09-28 20:46
Closing this because it has no actionable information. We'll add tests as we make changes and investments going forward.

**Closed by rynowak** 2021-09-28 20:46 UTC
Labels: kind/enhancement, technical debt
