### ISSUE TITLE
HttpClient couldn't find service when APP ID contains upper case characters

### ISSUE THREAD

**Issue by iahuohz** [dapr/dotnet-sdk#805] opened 2021-12-21 08:01 UTC
I craeted the classic MyBackEnd Web API application, and ran with:
```
dapr run --app-id MyBackEnd dotnet run MyBackEnd.dll
```
Please note that -app-id(MyBackEnd) contains some upper case characters(M, B, E)

Then I wrote a console application to call the web method as:
```
var httpClient = DaprClient.CreateInvokeHttpClient("MyBackEnd");
var results = await httpClient.GetAsync("WeatherForecast");
```
Finally, I ran the console application with:
```
dapr run --app-id myclient dotnet run
```
I got the following errors:
```
{"errorCode":"ERR_DIRECT_INVOKE","message":"fail to invoke, id: mybackend, err: couldn't find service: mybackend"}
```

However, when I ran MyBackEnd Web API application as(replace "MyBackEnd" with "mybackend"):
```
dapr run --app-id mybackend dotnet run MyBackEnd.dll
```
and also, change code in console application to:
```
var httpClient = DaprClient.CreateInvokeHttpClient("mybackend");    // replace "MyBackEnd" with "mybackend"
var results = await httpClient.GetAsync("WeatherForecast");
``` 
The program ran successfully.
The only difference was the -app-id："MyBackEnd" in the former case, and "mybackend" in the later case.

Still I found that calls made by DaprClient :
```
var daprClient = new DaprClientBuilder().Build(); 
var forecasts = await daprClient.InvokeMethodAsync<IEnumerable<WeatherForecast>>
             ( HttpMethod.Get, "MyBackEnd", "WeatherForecast");
```
will work with 
```
dapr run --app-id MyBackEnd dotnet run MyBackEnd.dll
```

So, my questing is: **Couldn't HttpClient recognize APP ID with upper case characters?**

Environments:
* Ubuntu 20.04
* Dapr CLI version: 1.5.1
* Dapr runtime version:1.5.1
* .NET Core SDK：6.0.101

**Comment by halspang** [comment] 2022-01-06 18:54
@iahuohz - Thanks for opening this issue! I'll try and dig in a little and see if this is a problem on the .NET side or if it's something that the runtime itself is doing.

**Comment by halspang** [comment] 2022-01-07 02:15
@iahuohz - I was able to reproduce this, but I think it's something that's happening outside of the dapr SDK. Http URLs are generally case-insensitive. Doing some step through debugging, it looks like the HttpClient that's returned from the System.Net code is what replaces the host (your app) with a lowercase version of it.

I'm not exactly sure where this happens, as I can't seem to make my debugger step into the system code and looking through it manually was proving to be very tedious. 

Given that this is in the system libraries and that you have a path forward with the DaprClient, I'm going to close this issue. Please feel free to reopen if you think this needs more work.

**Closed by halspang** 2022-01-07 02:15 UTC

**Comment by iahuohz** [comment] 2022-01-07 06:31
@halspang Got it!  Thanks a lot.
